sudo: required
services:
  - docker

before_install:
  - docker build -t pablorodriguez88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pablorodriguez88/docker-react npm run test

language: javascript
